steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/web-app:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/web-app:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mydeployment', 'mynode=gcr.io/sit323-23t1-oberli-bb88b7a/web-app:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster1'